
shared:
  automated_prs: &automated_prs
    - "author=cloudpossebot"
    - "author=github-actions[bot]"
    - "author=dependabot[bot]"
    - "author=renovate[bot]"

  default_branch: &default_branch
    - "base=main"
    - "base=master"

pull_request_rules:
  - name: "label automated pull requests"
    conditions:
      - or: *automated_prs
    actions:
      label:
        add:
          - "auto-update"

  - name: "label automated pull requests that update readme"
    conditions:
      - or: *automated_prs
      - "files~=README\\.md$"
    actions:
      label:
        add:
          - "readme"

  - name: "run terratest on automated pull requests that update terraform files"
    conditions:
      - or: *automated_prs
      - "files~=\\.tf$"
    actions:
      comment:
        message: "/terratest"

  - name: "merge automated PRs that only update the markdown files, images or videos"
    conditions:
      - "#check-pending=0"
      - "head~=auto-update/.*"
      - or: *default_branch
      - or: *automated_prs
      - "files~=\\.(md|gif|png|jpg|mp4)$"
    actions:
      label:
        add:
          - "no-release"
      merge:
        method: "squash"

  - name: "delete the head branch after merge"
    conditions:
      - "merged"
    actions:
      delete_head_branch: {}

  - name: "ask to resolve conflict"
    conditions:
      - "conflict"
    actions:
      comment:
        message: "This pull request now has conflicts. Could you fix it @{{author}}? ðŸ™"
      label:
        toggle:
          - conflict

  - name: "ask to not edit the readme"
    conditions:
      - files=README.md
      - -files=README.yaml
    actions:
      comment:
        message: |
          > [!IMPORTANT]
          > Do not edit the `README.md` directly. It's auto-generated from the `README.yaml`
          >

          Rebuild the `README.md` by running `make readme` and commit the changes.

          ```shell
          make init
          make readme
          ```

          Could you fix it @{{author}}? ðŸ™

  - name: "ask to rebuild readme"
    conditions:
      - files=README.yaml
      - -files=README.md
    actions:
      comment:
        message: |
          > [!IMPORTANT]
          > `README.md` is out of date.
          >

          Rebuild the `README.md` by running `make readme` and commit the changes.

          ```shell
          make init
          make readme
          ```

          Could you fix it @{{author}}? ðŸ™

  - name: "ask for title"
    conditions:
      - -title~=^[0-9A-Za-z]+
    actions:
      comment:
        message: |
            > [!IMPORTANT]
            > ## Title is necessary and should not be empty.
            >
            > Kindly provide a meaningful title for this Pull Request.

  - name: "ask for description"
    conditions:
      - -body~=[0-9A-Za-z]{10,}
      - -body~=(Describe high-level what changed)
    actions:
      comment:
        message: |
            > [!IMPORTANT]
            > ## Description is necessary and should not be empty.
            >
            > Kindly provide details with **what** was changed, **why** it was changed.

  - name: "remove outdated reviews"
    conditions:
      - or: *default_branch
    actions:
      dismiss_reviews:
        changes_requested: true
        approved: true
        message: "This Pull Request has been updated, so we're dismissing all reviews."

  - name: "remove triage label if approved"
    conditions:
      - '#approved-reviews-by>=1'
    actions:
      label:
        remove:
          - triage

  - name: close stale pull request
    conditions:
      - or: *default_branch
      - -closed
      - updated-at < 30 days ago
    actions:
      close:
        message: |
          This pull request looks stale. Feel free to reopen it if you think it's a mistake.

  - name: "close Pull Requests without files changed"
    conditions:
      - "#files=0"
    actions:
      label:
        add:
          - "no-changes"
      close:
        message: "This pull request has been automatically closed because there are no longer any changes."

  - name: welcome new contributors
    conditions:
      - and:
          - author!=dependabot[bot]
          - author!=mergify[bot]
    actions:
      comment:
        message: |
          Thanks @{{author}} for creating this pull request! 
          A maintainer will review your changes shortly.
          Please don't be discouraged if it takes a while.

          > [!TIP]
          > ## Need help or want to ask for a PR review?
          > Join us on [Slack](https://slack.cloudposse.com)

  - name: add triage label for new pull requests
    conditions:
      - '#label=0'
      - or:
        - created-at > 5 minutes ago
        - updated-at > 7 days ago
    actions:
      label:
        add:
          - triage

  - name: add "WIP" label when the title contains "WIP"
    conditions:
      - title~=WIP
    actions:
      label:
        toggle:
          - wip

  - name: mergeable
    conditions:
      - or: *default_branch
    actions:
      post_check:
        success_conditions:
          # Not a work in progress
          - "-title~=^(wip|WIP)"
          - "-label~=(WIP|wip|do-not-merge|do not merge|triage|duplicate|invalid|stale|wontfix|triage|feedback)"
          - '-draft'
          # Properly titled and described
          - "title~=(^[0-9A-Za-z]+)"
          - body~=[0-9A-Za-z]{10,}
          - -body~=(Describe high-level what changed)
          # Has reviews and no changes requested
          - '#approved-reviews-by>=1'
          - '#changes-requested-reviews-by>=1'
          - "#review-threads-unresolved=0"
          - "#commented-reviews-by=0"
          # Checks are passing
          - "#check-pending=0"
          - "#status-failure=0"
          - -status-failure~=^(terratest|terraform)
          # It's not closed or merged
          - -merged
          - -closed

        title: |
          {% if check_status == "success" %}
          This PR is ready to be merged
          {% else %}
          This PR is not ready to be merged
          {% endif %}
        summary: |
          {% if check_status == "failure" %}
          Your pull request needs to be updated before it can be merged.
          {% endif %}