
# These are YAML anchor definitions to avoid repetition and make the file more readable
shared:
  # Automated pull requests from bot users
  automated_prs: &automated_prs
    - "author=cloudpossebot"
    - "author=github-actions[bot]"
    - "author=dependabot[bot]"
    - "author=renovate[bot]"

  # Not a bot user
  not_a_bot: &not_a_bot
    - "-author=cloudpossebot"
    - "-author=github-actions[bot]"
    - "-author=dependabot[bot]"
    - "-author=renovate[bot]"

  # Default branches
  default_branch: &default_branch
    - "base=main"
    - "base=master"

  # Release branches
  release_branch: &release_branch
    - "base~=^release/v\\d{1,2}$"

  # Not a work in progress
  not_wip: &not_wip
    - "-title~=^(wip|WIP)"
    - "-label~=(WIP|wip|do-not-merge|do not merge|triage|duplicate|invalid|stale|wontfix|triage|feedback)"
    - '-draft'

  # Properly titled and described
  pr_metadata: &pr_metadata
    - "title~=(^[0-9A-Za-z]+)"
    - body~=[0-9A-Za-z]{10,}
    - -body~=(Describe high-level what changed)

  # Has reviews and no changes requested
  is_approved: &is_approved
    - '#approved-reviews-by>=1'
    - '#changes-requested-reviews-by>=1'
    - "#review-threads-unresolved=0"
    - "#commented-reviews-by=0"

  # Checks are passing
  checks_passing: &checks_passing
    - "#check-pending=0"
    - "#status-failure=0"

  # Only for terraform files
  require_terraform_checks_passing: &require_terraform_checks_passing
    - or:
      - "-files~=\\.tf$"
      - and:
        - "check-success=test/bats"
        - "check-success=test/terratest"
        - -status-failure~=^(terratest|terraform)$

  require_codeowners_checks_passing: &require_codeowners_checks_passing
    - or:
      - "-files=CODEOWNERS"
      - and:
        - "check-success=validate-codeowners"

  # It's not closed or merged
  is_open: &is_open
    - -merged
    - -closed

  # README.md is updated together with README.yaml
  readme_updated: &readme_updated
    - or:
      - and:
        - -files=README.md
        - -files=README.yaml
      - and:
        - files=README.md
        - files=README.yaml

# All the rules for the Pull Request
pull_request_rules:
  - name: "label automated pull requests"
    conditions:
      - or: *automated_prs
      - *is_open
    actions:
      label:
        add:
          - "auto-update"

  - name: "label automated pull requests that update readme"
    conditions:
      - *is_open
      - or: *automated_prs
      - "files=README.md"
    actions:
      label:
        add:
          - "readme"

  - name: "run terratest on automated pull requests that update terraform files"
    conditions:
      - *is_open
      - or: *automated_prs
      - "files~=\\.tf$"
    actions:
      comment:
        message: "/terratest"

  - name: "merge automated PRs that only update the markdown files, images or videos"
    conditions:
      - *is_open
      - "#check-pending=0"
      - "head~=auto-update/.*"
      - or: *default_branch
      - or: *automated_prs
      - "files~=\\.(md|gif|png|jpg|mp4)$"
    actions:
      label:
        add:
          - "no-release"
      merge:
        method: "squash"

  - name: "delete the head branch after merge"
    conditions:
      - "merged"
    actions:
      delete_head_branch: {}

  - name: "ask to resolve conflict"
    conditions:
      - *is_open
      - "conflict"
    actions:
      comment:
        message: "This pull request now has conflicts. Could you fix it @{{author}}? 🙏"
      label:
        toggle:
          - conflict

  - name: "ask to not edit the readme"
    conditions:
      - *is_open
      - files=README.md
      - -files=README.yaml
    actions:
      comment:
        message: |
          > [!IMPORTANT]
          > Do not edit the `README.md` directly. It's auto-generated from the `README.yaml`
          >

          Rebuild the `README.md` by running `make readme` and commit the changes.

          ```shell
          make init
          make readme
          ```

          Could you fix it @{{author}}? 🙏

  - name: "ask to rebuild readme"
    conditions:
      - *is_open
      - files=README.yaml
      - -files=README.md
    actions:
      comment:
        message: |
          > [!IMPORTANT]
          > `README.md` is out of date.
          >

          Rebuild the `README.md` by running `make readme` and commit the changes.

          ```shell
          make init
          make readme
          ```

          Could you fix it @{{author}}? 🙏

  - name: "ask for title"
    conditions:
      - *is_open
      - -title~=^[0-9A-Za-z]+
    actions:
      comment:
        message: |
          > [!IMPORTANT]
          > ## Title is necessary and should not be empty.
          >
          > Kindly provide a meaningful title for this Pull Request.

  - name: "ask for description"
    conditions:
      - *is_open
      - -body~=[0-9A-Za-z]{10,}
      - -body~=(Describe high-level what changed)
    actions:
      comment:
        message: |
          > [!IMPORTANT]
          > ## Description is necessary and should not be empty.
          >
          > Kindly provide details with **what** was changed, **why** it was changed.

  - name: "remove outdated reviews"
    conditions:
      - *is_open
      - or: *default_branch
    actions:
      dismiss_reviews:
        changes_requested: true
        approved: true
        message: "This Pull Request has been updated, so we're dismissing all reviews."

  - name: "remove triage label if approved"
    conditions:
      - *is_open
      - '#approved-reviews-by>=1'
    actions:
      label:
        remove:
          - triage

  - name: close stale pull request
    conditions:
      - *is_open
      - or: *default_branch
      - -closed
      - updated-at < 30 days ago
    actions:
      close:
        message: |
          This pull request looks stale. Feel free to reopen it if you think it's a mistake.

  - name: remove certain labels on close
    conditions:
      - closed
    actions:
      label:
        remove:
          - triage

  - name: "close Pull Requests without files changed"
    conditions:
      - *is_open
      - "#files=0"
    actions:
      label:
        add:
          - "no-changes"
      close:
        message: "This pull request has been automatically closed because there are no longer any changes."

  - name: welcome new contributors
    conditions:
      - *is_open
      - and: *not_a_bot
    actions:
      comment:
        message: |
          Thanks @{{author}} for creating this pull request! 
          A maintainer will review your changes shortly.
          Please don't be discouraged if it takes a while.

          > [!TIP]
          > ## Need help or want to ask for a PR review to be expedited?
          > Join us on [Slack](https://slack.cloudposse.com) in the `#pr-reviews` channel.

  - name: add triage label for new pull requests
    conditions:
      - *is_open
      - '#label=0'
      - or:
        - created-at > 5 minutes ago
        - updated-at > 7 days ago
    actions:
      label:
        add:
          - triage

  - name: add "WIP" label when the title contains "WIP"
    conditions:
      - *is_open
      - title~=WIP
    actions:
      label:
        toggle:
          - wip

  - name: mergeable
    conditions:
      - *is_open
      - or: *default_branch
    actions:
      post_check:
        success_conditions:
          - and:
            - *not_wip
            - *pr_metadata
            - *readme_updated
            - *is_approved
            - *checks_passing
            - *require_terraform_checks_passing
            - *require_codeowners_checks_passing

        title: |
          {% if check_status == "success" %}
          This PR is ready to be merged
          {% else %}
          This PR is not ready to be merged
          {% endif %}
        summary: |
          {% if check_status == "failure" %}
          Your pull request needs to be updated before it can be merged.
          {% endif %}