
shared:
  automated_prs: &automated_prs
    - "author=cloudpossebot"
    - "author=github-actions[bot]"
  default_branch: &default_branch
    - "base=main"
    - "base=master"

pull_request_rules:
  - name: "label automated pull requests"
    conditions:
      - or: *automated_prs
    actions:
      label:
        add:
          - "auto-update"

  - name: "label automated pull requests that update readme"
    conditions:
      - or: *automated_prs
      - "files~=README\\.md$"
    actions:
      label:
        add:
          - "readme"

  - name: "merge automated PRs that only update the markdown files, images or videos"
    conditions:
      - "#check-pending=0"
      - "head~=auto-update/.*"
      - or: *default_branch
      - or: *automated_prs
      - "files~=\\.(md|gif|png|jpg|mp4)$"
    actions:
      label:
        add:
          - "no-release"
      merge:
        method: "squash"

  - name: "delete the head branch after merge"
    conditions:
      - "merged"
    actions:
      delete_head_branch: {}

  - name: "ask to resolve conflict"
    conditions:
      - "conflict"
    actions:
      comment:
        message: "This pull request now has conflicts. Could you fix it @{{author}}? 🙏"

  - name: "remove outdated reviews"
    conditions:
      - or: *default_branch
    actions:
      dismiss_reviews:
        changes_requested: true
        approved: true
        message: "This Pull Request has been updated, so we're dismissing all reviews."

  - name: close stale pull request
    conditions:
      - or: *default_branch
      - -closed
      - updated-at < 30 days ago
    actions:
      close:
        message: |
          This pull request looks stale. Feel free to reopen it if you think it's a mistake.