name: Scheduled Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "scaffolding/*"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  scaffolding:
    runs-on: ubuntu-latest
    environment: security
    steps:
      - name: Run organizational action
        uses: cloudposse-github-actions/.github@repo-scaffolding
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
