name: auto-release

on:
  push:
    branches:
      - main
      - master
      - production

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    steps:
      # Get PR from merged commit to master
      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        with:
          publish: ${{ !contains(steps.get-merged-pull-request.outputs.labels, 'no-release') }}
          prerelease: false
          config-name: auto-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
