name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write
  deployments: write
  
jobs:
  perform:
    uses: cloudposse-github-actions/.github/.github/workflows/shared-release-branches.yml@main
    secrets: inherit
