---
name: Release Branch
on:
  push:
    branches:
      - main
      - release/**
    # This .github organization is a special case for the release branch
    # We want to cut releases when github reusable/shared workflows change.
    # So we should not skip .github/** paths
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'test/**'
      - 'README.*'

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  readme:
    uses: cloudposse-github-actions/.github/.github/workflows/shared-readme.yml@main
    name: "ci"
    with:
      runs-on: '["ubuntu-latest"]'
    secrets: inherit

  release:
    needs: [ readme ]
    name: "ci"
    uses: cloudposse-github-actions/.github/.github/workflows/shared-auto-release.yml@main
    with:
      publish: ${{ inputs.publish }}
    secrets: inherit
