name: Scheduled Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  readme:
    runs-on: ubuntu-latest
    environment: security
    steps:
      - uses: actions/create-github-app-token@v1
        id: github-app
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cloudposse-github-actions/readme@main
        with:
          token: ${{ steps.github-app.outputs.token }}
          readme_enabled: true
          banner_enabled: true
          commit_method: 'pr'

  scaffolding:
    runs-on: ubuntu-latest
    environment: security
    steps:
      - name: Run organizational action
        uses: cloudposse-github-actions/.github@v0
        with:
          github_app_id: ${{ vars.GH_APP_ID }}
          github_app_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}